services:
  - type: web
    name: foodies-api
    runtime: docker
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/foodiesapi-0.0.1-SNAPSHOT.jar"
    plan: free
